name: OpenSCENARIO Checker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Checker Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: OpenSCENARIO checker action
      uses: ahege/openscenario.ci.test@v3.0.2
      with:
        CONF_FILE: conf/conf.yml
        BASE_DIR: targetFolder
        CHECKER_JAR_FILE: conf/net.asam.openscenario.checker.example-0.9.0.jar
       
        
