name: OpenSCENARIO Checker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Checker Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: github.com/ahege/openscenario.ci.test/checkOscAction@1.0.0
      with:
        CONF_FILE: conf/conf.yml
        BASE_DIR: targetFolder
        CHECKER_JAR_FILE: conf/net.asam.openscenario.checker.example-0.9.0.jar
        